- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: atb-rotation-key
         group: "launch-wizard-5"
         region: "us-east-1"
         instance_type: t2.micro
         image: "ami-234c4335"
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo-ansible
         instance_tags:
            Name: Demo-ansible
      register: ec2
    - name: Add new instance to host group
  #    local_action:  add_host path /Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/Comcast/ecs_ansible_tf/ansible/hosts hostname="{{ item.public_ip }}" ansible_ssh_user=ubuntu groups=apache
      add_host: hostname={{ item.public_ip }} groupname=apache
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: configuration play
  hosts: apache
  become: yes
  remote_user: ubuntu
  #gather_facts: True
  tasks:
      - name: Install
        service: name=apache2 state=started

      - name: Configure apache
        copy: 'src=install_apache.sh dest=/home/ubuntu/install_apache-script.sh mode=a+x'
        copy: 'src=landing.html dest=/var/www/html/landing.html'
        copy: 'src=apache2.conf dest=/home/ubuntu/apache2.conf'
      - name: execute script
        command: '/home/ubuntu/install_apache-script.sh'
