- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Create a security group
      local_action:
          module: ec2_group
          name: "SRE challenge"
          description: Security Group for webserver Servers
          region: "us-east-1"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Provision a set of instances
      ec2:
         key_name: atb-rotation-key
         group: "SRE challenge"
         region: "us-east-1"
         instance_type: t2.micro
         image: "ami-234c4335"
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo-ansible
         instance_tags:
            Name: Demo-ansible
      register: ec2
    - name: Add new instance to host group
  #    local_action:  add_host path /Users/sasikumaranandan/Desktop/ATB_Projects/DevOps/Comcast/ecs_ansible_tf/ansible/hosts hostname="{{ item.public_ip }}" ansible_ssh_user=ubuntu groups=apache
      add_host: hostname={{ item.public_ip }} groupname=apache
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- include: config-apache2.yml
