- hosts: apache
  vars:
    http_port: 80
    https_port: 443
    domain: ec2-174-129-48-56.compute-1.amazonaws.com
  sudo: yes
  remote_user: ubuntu
  gather_facts: True
  tasks:
    - shell: "(cd /; mkdir /home/ubuntu/madebyansible; sudo apt-get update && sudo apt-get upgrade; sudo apt-get -y install apache2 apache2-doc apache2-utils)"
      async: 10
      poll: 0
# Copying apache config files
    - copy: src=files/install_apache.sh dest=/home/ubuntu/install_apache-script.sh mode=a+x
    - copy: 'src=files/landing.html dest=/var/www/html/landing.html'
    - copy: 'src=files/apache2.conf dest=/home/ubuntu/apache2.conf'
    - copy: 'src=certs/apache2.crt dest=/etc/ssl/certs/apache2.crt'
    - copy: 'src=certs/apache2.key dest=/etc/ssl/certs/apache2.key'
    - command: /home/ubuntu/install_apache-script.sh
  #  - lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
    - name: create virtual host file
      template: src=files/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      command: service apache2 restart
# Validating the apache config
    - uri:
        url: http://ec2-174-129-48-56.compute-1.amazonaws.com
        return_content: yes
        validate_certs: False
      register: webpage
    - name: Fail if Hello is not in the page content
      fail:
      when: "'Hello' not in webpage.content"
    - uri:
        url: https://ec2-174-129-48-56.compute-1.amazonaws.com
        return_content: yes
        validate_certs: False
      register: webpage
    - name: Fail if Hello is not in the page content
      fail:
      when: "'Hello' not in webpage.content"
